import {readFile,writeFile} from 'node:fs/promises';import {insidePolygon} from '../src/landmark-layout.js';
const raw=JSON.parse(await readFile('assets/places/zoo-osm.json')),nodes=new Map(raw.elements.filter(e=>e.type==='node').map(e=>[e.id,e])),ways=raw.elements.filter(e=>e.type==='way'&&e.tags).map(e=>({...e,p:e.nodes.map(id=>nodes.get(id)).filter(Boolean).map(p=>[(p.lon-121.54)*100800,(25.05-p.lat)*111320])}));
const boundary=ways.find(e=>e.id===135913533).p,paths=ways.filter(e=>e.tags.highway&&e.tags.access!=='private'),buildings=ways.filter(e=>e.tags.building),zones=ways.filter(e=>e.tags.attraction==='animal'&&!e.tags.building);
const distance=(p,a,b)=>{const dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dz)/(dx*dx+dz*dz||1)));return Math.hypot(p[0]-a[0]-dx*t,p[1]-a[1]-dz*t);};
const habitats=[];for(const [id,species,count] of [[4371227973,'giraffe',4],[11841265146,'zebra',7],[11841263743,'elephant',3],[4378252423,'flamingo',12]]){
 const n=nodes.get(id),p=[(n.lon-121.54)*100800,(25.05-n.lat)*111320];let clearance=35;for(const w of [...paths,...buildings])for(let i=1;i<w.p.length;i++)clearance=Math.min(clearance,distance(p,w.p[i-1],w.p[i]));const radius=Math.min(28,clearance-3);if(radius<4)throw Error(`No clear habitat space: ${species}`);habitats.push({id,species,count,x:p[0],z:p[1],radius,name:n.tags['name:en']||n.tags.name||species});
}
let seed=7;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const xs=boundary.map(p=>p[0]),zs=boundary.map(p=>p[1]),trees=[];
for(let i=0;i<12000&&trees.length<900;i++){const p=[Math.min(...xs)+rand()*(Math.max(...xs)-Math.min(...xs)),Math.min(...zs)+rand()*(Math.max(...zs)-Math.min(...zs))];if(!insidePolygon(p,boundary)||buildings.some(b=>insidePolygon(p,b.p))||habitats.some(h=>Math.hypot(h.x-p[0],h.z-p[1])<h.radius+4))continue;if(paths.some(w=>w.p.some((a,i)=>i&&distance(p,w.p[i-1],a)<5)))continue;trees.push([...p,4+rand()*6]);}
await writeFile('public/data/zoo.json',JSON.stringify({source:'OSM zoo boundary, public paths and animal POIs; illustrative circular habitats and animal counts',boundary,habitats,trees,zones:zones.map(e=>({id:e.id,name:e.tags.name,p:e.p}))}));console.log(habitats.map(h=>({species:h.species,radius:h.radius})),trees.length,'trees');
