import {createZooGrounds} from './zoo-grounds.js';
import {createZooGondola} from './zoo-gondola.js';
import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';import {terrainHeight,drapeGeometry} from './terrain.js';

export function animalPosition(h,index,time){const phase=index*Math.PI*2/h.count+time*({panda:.035,'red-panda':.10,monkey:.12,penguin:.055,elephant:.035}[h.species]??.075),radius=Math.max(.5,h.radius-3.3)*(.7+.2*(index%3)/2);return {x:h.x+Math.cos(phase)*radius,z:h.z+Math.sin(phase)*radius*.7,angle:Math.atan2(-Math.sin(phase),Math.cos(phase)*.7),phase};}
export async function createZoo(scene,terrain,{reducedMotion=false}={}){
 const response=await fetch('/data/zoo.json',{cache:'no-cache'});if(!response.ok)throw Error('Zoo map unavailable');const data=await response.json(),group=new THREE.Group();group.name='Taipei Zoo grounds';scene.add(group);
 const grounds=createZooGrounds(group,data,terrain),gondola=createZooGondola(scene,data,terrain,{reducedMotion});
 const dummy=new THREE.Object3D(),color=new THREE.Color(),trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.22,.38,1,6),new THREE.MeshStandardMaterial({color:'#735b43',roughness:1}),data.trees.length),leaves=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),new THREE.MeshStandardMaterial({color:'#ffffff',roughness:1}),data.trees.length);
 data.trees.forEach(([x,z,h],i)=>{const y=terrainHeight(terrain,x,z);dummy.position.set(x,y+h*.28,z);dummy.scale.set(1,h*.56,1);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);dummy.position.y=y+h*.75;dummy.scale.set(h*.4,h*.48,h*.4);dummy.updateMatrix();leaves.setMatrixAt(i,dummy.matrix);leaves.setColorAt(i,color.setHSL(.24+(i%7)*.006,.22,.17+(i%5)*.012));});leaves.castShadow=true;leaves.receiveShadow=true;group.add(trunks,leaves);
 const clock={value:0},mat=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.85});mat.onBeforeCompile=s=>{s.uniforms.animalTime=clock;s.vertexShader='attribute float gait;uniform float animalTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>
 float phase=instanceMatrix[3].x*.37+instanceMatrix[3].z*.21;transformed.z+=sin(animalTime*2.8+phase)*gait*.12;`);};
 const loader=new GLTFLoader(),animals=[];
 for(const h of data.habitats){const gltf=await loader.loadAsync(`/models/zoo-${h.species}.glb`),parts=[];gltf.scene.updateMatrixWorld(true);gltf.scene.traverse(o=>{if(!o.isMesh)return;const g=o.geometry.clone().applyMatrix4(o.matrixWorld);for(const key of Object.keys(g.attributes))if(key!=='position'&&key!=='normal')g.deleteAttribute(key);const p=g.attributes.position,colors=new Float32Array(p.count*3),gait=new Float32Array(p.count),limit={giraffe:1.9,zebra:.85,elephant:1,flamingo:.8,panda:.45,'red-panda':.3,monkey:.4,penguin:.2}[h.species];for(let i=0;i<p.count;i++){o.material.color.toArray(colors,i*3);gait[i]=p.getY(i)<limit?Math.sign(p.getX(i)*p.getZ(i)):0;}g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.setAttribute('gait',new THREE.BufferAttribute(gait,1));if(!g.index)g.setIndex(Array.from({length:p.count},(_,i)=>i));parts.push(g);});const geometry=mergeGeometries(parts);parts.forEach(g=>g.dispose());const mesh=new THREE.InstancedMesh(geometry,mat,h.count);mesh.name=`Zoo animals: ${h.species}`;mesh.frustumCulled=false;mesh.count=0;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);scene.add(mesh);animals.push({h,mesh});}
 const clip=new THREE.Vector3(),stats={totalAnimals:data.habitats.reduce((n,h)=>n+h.count,0),visibleAnimals:0,species:{},drawCalls:0,updateHz:0},center=data.habitats[0];let lastTick=-10;
 function update(time,camera,quality,enabled=true){const low=quality==='low';grounds.update(camera);gondola.update(time,camera,quality,enabled);group.visible=Math.hypot(camera.position.x-center.x,camera.position.z-center.z)<(low?1800:2600)&&camera.position.y<900;if(document.hidden)return;if(time-lastTick<1/(low?10:20)&&enabled)return;lastTick=time;clock.value=reducedMotion?0:time;stats.visibleAnimals=0;stats.drawCalls=0;stats.updateHz=low?10:20;
  for(const {h,mesh} of animals){let count=0;if(enabled)for(let i=0;i<h.count;i++){const p=animalPosition(h,i,reducedMotion?0:time),y=terrainHeight(terrain,p.x,p.z)+.13;clip.set(p.x,y+2,p.z);if(clip.distanceTo(camera.position)>(low?250:650))continue;clip.project(camera);if(clip.z< -1||clip.z>1||Math.abs(clip.x)>1.1||Math.abs(clip.y)>1.1)continue;dummy.position.set(p.x,y,p.z);dummy.rotation.set(0,p.angle,0);dummy.scale.setScalar(.88+(i%3)*.09);dummy.updateMatrix();mesh.setMatrixAt(count++,dummy.matrix);}mesh.count=count;mesh.visible=count>0;mesh.instanceMatrix.needsUpdate=true;stats.species[h.species]=count;stats.visibleAnimals+=count;if(count)stats.drawCalls++;}
 }
 function streetView(target){const h=data.habitats.reduce((a,b)=>Math.hypot(a.x-target.x,a.z-target.z)<Math.hypot(b.x-target.x,b.z-target.z)?a:b);return {pos:new THREE.Vector3(h.x+h.radius+12,terrainHeight(terrain,h.x,h.z)+18,h.z+h.radius+18),target:new THREE.Vector3(h.x,terrainHeight(terrain,h.x,h.z)+2,h.z)};}
 return {update,stats,animals,data,streetView,grounds,gondola};
}
