import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';import {terrainHeight,drapeGeometry} from './terrain.js';

export function animalPosition(h,index,time){const phase=index*Math.PI*2/h.count+time*(h.species==='flamingo'?.055:.075),radius=Math.max(.5,h.radius-3.3)*(.7+.2*(index%3)/2);return {x:h.x+Math.cos(phase)*radius,z:h.z+Math.sin(phase)*radius*.7,angle:Math.atan2(-Math.sin(phase),Math.cos(phase)*.7),phase};}
export async function createZoo(scene,terrain,{reducedMotion=false}={}){
 const response=await fetch('/data/zoo.json',{cache:'no-cache'});if(!response.ok)throw Error('Zoo map unavailable');const data=await response.json(),group=new THREE.Group();group.name='Taipei Zoo grounds';scene.add(group);
 function surface(poly,color,offset){const shape=new THREE.Shape(poly.map(p=>new THREE.Vector2(p[0],-p[1]))),g=drapeGeometry(new THREE.ShapeGeometry(shape).rotateX(-Math.PI/2),terrain,offset),mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:1,side:THREE.DoubleSide}));mesh.receiveShadow=true;group.add(mesh);}
 surface(data.boundary,'#53684a',.025);
 const rails=[];for(const h of data.habitats){const ring=Array.from({length:40},(_,i)=>[h.x+Math.cos(i/40*Math.PI*2)*h.radius,h.z+Math.sin(i/40*Math.PI*2)*h.radius]);surface(ring,h.species==='flamingo'?'#568682':'#a7976e',.09);
  for(let i=0;i<ring.length;i++){const a=ring[i],b=ring[(i+1)%ring.length],y=terrainHeight(terrain,...a),yb=terrainHeight(terrain,...b),dx=b[0]-a[0],dz=b[1]-a[1];rails.push(new THREE.BoxGeometry(.14,1.3,.14).translate(a[0],y+.65,a[1]));for(const height of [.55,1.15]){const g=new THREE.BoxGeometry(.08,.08,Math.hypot(dx,dz,yb-y)),m=new THREE.Matrix4(),o=new THREE.Object3D();o.position.set((a[0]+b[0])/2,(y+yb)/2+height,(a[1]+b[1])/2);o.rotation.y=Math.atan2(dx,dz);o.rotateX(-Math.atan2(yb-y,Math.hypot(dx,dz)));o.updateMatrix();m.copy(o.matrix);rails.push(g.applyMatrix4(m));}}
 }
 const fence=new THREE.Mesh(mergeGeometries(rails),new THREE.MeshStandardMaterial({color:'#7a7563',roughness:.9}));rails.forEach(g=>g.dispose());fence.receiveShadow=true;group.add(fence);
 const dummy=new THREE.Object3D(),color=new THREE.Color(),trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.22,.38,1,6),new THREE.MeshStandardMaterial({color:'#735b43',roughness:1}),data.trees.length),leaves=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),new THREE.MeshStandardMaterial({color:'#ffffff',roughness:1}),data.trees.length);
 data.trees.forEach(([x,z,h],i)=>{const y=terrainHeight(terrain,x,z);dummy.position.set(x,y+h*.28,z);dummy.scale.set(1,h*.56,1);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);dummy.position.y=y+h*.75;dummy.scale.set(h*.4,h*.48,h*.4);dummy.updateMatrix();leaves.setMatrixAt(i,dummy.matrix);leaves.setColorAt(i,color.setHSL(.24+(i%7)*.006,.22,.17+(i%5)*.012));});leaves.castShadow=true;leaves.receiveShadow=true;group.add(trunks,leaves);
 const clock={value:0},mat=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.85});mat.onBeforeCompile=s=>{s.uniforms.animalTime=clock;s.vertexShader='attribute float gait;uniform float animalTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>
 float phase=instanceMatrix[3].x*.37+instanceMatrix[3].z*.21;transformed.z+=sin(animalTime*2.8+phase)*gait*.12;`);};
 const loader=new GLTFLoader(),animals=[];
 for(const h of data.habitats){const gltf=await loader.loadAsync(`/models/zoo-${h.species}.glb`),parts=[];gltf.scene.updateMatrixWorld(true);gltf.scene.traverse(o=>{if(!o.isMesh)return;const g=o.geometry.clone().applyMatrix4(o.matrixWorld);for(const key of Object.keys(g.attributes))if(key!=='position'&&key!=='normal')g.deleteAttribute(key);const p=g.attributes.position,colors=new Float32Array(p.count*3),gait=new Float32Array(p.count),limit={giraffe:1.9,zebra:.85,elephant:1,flamingo:.8}[h.species];for(let i=0;i<p.count;i++){o.material.color.toArray(colors,i*3);gait[i]=p.getY(i)<limit?Math.sign(p.getX(i)*p.getZ(i)):0;}g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.setAttribute('gait',new THREE.BufferAttribute(gait,1));parts.push(g);});const geometry=mergeGeometries(parts);parts.forEach(g=>g.dispose());const mesh=new THREE.InstancedMesh(geometry,mat,h.count);mesh.name=`Zoo animals: ${h.species}`;mesh.frustumCulled=false;mesh.count=0;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);scene.add(mesh);animals.push({h,mesh});}
 const clip=new THREE.Vector3(),stats={totalAnimals:data.habitats.reduce((n,h)=>n+h.count,0),visibleAnimals:0,species:{},drawCalls:0,updateHz:0},center=data.habitats[0];let lastTick=-10;
 function update(time,camera,quality,enabled=true){const low=quality==='low';group.visible=Math.hypot(camera.position.x-center.x,camera.position.z-center.z)<(low?1800:2600)&&camera.position.y<900;if(document.hidden)return;if(time-lastTick<1/(low?10:20)&&enabled)return;lastTick=time;clock.value=reducedMotion?0:time;stats.visibleAnimals=0;stats.drawCalls=0;stats.updateHz=low?10:20;
  for(const {h,mesh} of animals){let count=0;if(enabled)for(let i=0;i<h.count;i++){const p=animalPosition(h,i,reducedMotion?0:time),y=terrainHeight(terrain,p.x,p.z)+.13;clip.set(p.x,y+2,p.z);if(clip.distanceTo(camera.position)>(low?250:650))continue;clip.project(camera);if(clip.z<0||clip.z>1||Math.abs(clip.x)>1.1||Math.abs(clip.y)>1.1)continue;dummy.position.set(p.x,y,p.z);dummy.rotation.set(0,p.angle,0);dummy.scale.setScalar(.88+(i%3)*.09);dummy.updateMatrix();mesh.setMatrixAt(count++,dummy.matrix);}mesh.count=count;mesh.visible=count>0;mesh.instanceMatrix.needsUpdate=true;stats.species[h.species]=count;stats.visibleAnimals+=count;if(count)stats.drawCalls++;}
 }
 function streetView(target){const h=data.habitats.reduce((a,b)=>Math.hypot(a.x-target.x,a.z-target.z)<Math.hypot(b.x-target.x,b.z-target.z)?a:b);return {pos:new THREE.Vector3(h.x+h.radius+12,terrainHeight(terrain,h.x,h.z)+18,h.z+h.radius+18),target:new THREE.Vector3(h.x,terrainHeight(terrain,h.x,h.z)+2,h.z)};}
 return {update,stats,animals,data,streetView};
}
